[project]
name = "lohitmail"
version = "0.1.0"
description = "Send templated emails from Google Sheets data."
authors = []
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "gspread",
    "google-auth",
    "python-dotenv (>=1.2.2,<2.0.0)",
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
